Blog data
benjaminmodayil/blendid-test pull request #4
Opened 2017-07-14 14:29 UTC by benjaminmodayil

I got the data for the routes working! I still need to double-click on everything... And I think Webpack's auto-refresh is broken, but everything else is nice! 

୧[ * ಡ ▽ ಡ * ]୨

2017-07-14 20:05 UTC, mzlock requested changes

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/ArticlePreview.js
> +  componentWillMount() {}
Still need this? Doesn't look like it's doing anything

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/ArticlePreview.js
> +    // console.log(this.props)
deleeeete

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/ArticlePreview.js
> +          <Link to={`/article/${postInfo.id}`}><h1>{postInfo.title}</h1></Link>
Since `/article/${postInfo.id}` is referenced a number of times, it might be good to store it in a variable -- that way if it ever changes, you only have to change one line of code

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/ArticlePreview.js
> +            </small>
`<small>` tags are used more for legal or "fine print" type text.  Use CSS to make these smaller instead

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/ArticlePreview.js
> +              <Link to="/author" data-id={postInfo.author.id}>{postInfo.author.name}</Link>
You set up the routes for authors, right?  Update that URL to include the `id`

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/Blog.js
> +    // console.log(this.props.params)
deleeeeete

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Article.js
> +    this.state = { posts: {} }
But you only need one `post` in state.  This should be singular.

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Article.js
> +    this.setState({ posts: { newPosts } })
You're doing way more work here than you need to.  This method should:

- find only the post you need
- add the needed author to only that post
- save that 1 post to state

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Article.js
>    }
get rid of all the unneeded console logs

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Article.js
> +          <Aside post={this.state.posts.newPosts[this.props.params.id - 1]} />
Once you fix the logic above, this can just be `this.state.post`.

Try to avoid doing _any_ logic inside your render function, except maybe calculating class names. I would count picking a post out of a list of posts as logic.

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Article.js
> +          <Aside post={this.state.posts.newPosts[this.props.params.id - 1]} />
Better yet, add `const { post } = this.state` at the top of `render()` and then you can use `post={ post }` on your components

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Aside.js
>              His most famous writings are Alice's Adventures in Wonderland, its sequel Through the Looking-Glass, which
Still need this hard-coded text?

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Header.js
> +        <div className="article-header__bg" />
This is applying the yellow, right?  Why not just set a background color on the whole header?

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Meta.js
> +          <span><a href="">{post.meta.categories.join(', ')}</a></span>
Each of those categories needs to be a new `<a>`.  Rethink your templating here.

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Meta.js
> +            <a href="">{post.meta.tags.join(', ')}</a>
Same...  Each tag should be a new `<a>`, so rethink your templating.

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/article/Text.js
> +            <Link to="/author">{post.author.name}</Link>
You need to add the `id` to that `href`

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/author/AuthorBio.js
> +  // const { posts } = this.props
deleeete

2017-07-14 20:05 UTC, mzlock commented on src/javascripts/components/blog/author/AuthorBio.js
> +          <img src="/images/blog-title.svg" alt="Aspiring Writer's Alley - Link to Home" />
Just make this "Aspiring Writer's Alley - Home".  The "Link to" is going to be redundant since a screen reader will say it's a link.

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/_placeholders.scss
> +// mixin
extra note?

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/base/_elements.scss
> +// CHANGE TO .WRAPPER
I recommend adding `#TODO` to anything like this.  It's a good string to search for, when you're ready to clean up a project

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/base/_typography.scss
> +  font-family: $f-mont;
Be sure to add fall-backs to your fonts.

`font-family: $f-mont, sans-serif;`

That way if your font fails to load, the user gets a fall-back

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/author/_authorBio.scss
> +    &:first-of-type {
:+1:

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +.article-inner__titleCard {
no camel case!

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +    margin-bottom: 3rem;
you can do two lines of code in one:
`margin: 0 auto 3rem;`

the `margin` short-hand takes margins in order of: `top left bottom right`.  Of course, if you don't specify the `bottom` value, it uses the top, and if you don't specify the `right` value, it uses the left, which is why `margin: 0 auto;` works

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +    @include fz(56);
I like to do `@include`(s) first in case you need to override any styles set in the include

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +    &:hover, &:focus {
We prefer selectors on new lines:
```
&:hover,
&:focus {
```

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +      url("/images/alice-in-wonderland-big.png");
If you were working with a CMS, then this image would need to be set in the template somehow, not in a CSS file. Any ideas on how you'd do that?

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +.article-header__bg {
new line in between

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +  z-index: 20;
I think I questioned the need for this div back in the HTML...

Is the intent that this fill its parent div? What does your `rd` function do again?  If you want to fill the parent, that that should just be `width: 100%;`

Ohhhh. right, this is that max-width on `<main>` getting in the way of styling things, isn't it?

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +  width: rd(950, 1440);
you shouldn't need a width on this at all.   It'll try to fill the screen until it hits your max-width.  So, what is this for?

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +  }
This is done twice

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +  top: -100px;
just make this a `margin-top: -100px;` and the rest of your page should flow better.

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +  top: -80px;
Change the `top: -100px` to a margin and them you can get rid of this - maybe give it a margin-top of `20px` instead

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +  }
done twice

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_article.scss
> +    &:first-of-type {
new line between things!!

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articleAuthorBio.scss
> +  max-width: 1200px;
you're doing these max-widths a looooot.  Make that `.wrapper` I mentioned :)

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articleAuthorBio.scss
> +  }
done twice

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articleAuthorBio.scss
> +  }
We typically do responsive styles the other way around.  You style for the mobile version first (so the browser can run less code when you're on a less-optimal device) and then add media queries for the _larger_ version

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articleIndex.scss
> +  header {
new liiiiiiiines

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articleIndex.scss
> +  header {
I'm gonna have to give you a New Line Jar to put a penny into every time I have to make this comment on your code.

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articleIndex.scss
> +    max-width: 100%;
I thought I saw `max-width: 100%` as a universal style on images somewhere in your code.

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articleIndexNav.scss
> +    &:nth-of-type(2) {
you can also use `&:nth-child()`, which you can use in 2 ways:

`&:nth-child(odd)` (or even) for alternating styles

`&:nth-child(2n)` does the same thing (style every 2nd child), but you can change the formula in there, like `&:nth-child(3n)` for every third or `&:nth-child(4n + 1)` every 4th, but offset that by 1

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articlePreview.scss
> +  p {
new line

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/blog/_articlePreview.scss
> +  .-imageContainer {
new line

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/chat/_chat.scss
> +//write a class for this nav
#TODO

2017-07-14 20:05 UTC, mzlock commented on src/stylesheets/components/chat/_messageInput.scss
> +  border: 0 solid transparent;
do you need just `border: none` ?  Or `border-width: 0;`

2017-07-14 20:25 UTC, benjaminmodayil commented on src/stylesheets/components/blog/_article.scss
> +    margin-bottom: 3rem;
'Sigh', this is a very bad habit of mine where I apply the ```margin: 0 auto;```  then I override it with another...

2017-07-14 20:30 UTC, benjaminmodayil commented on src/stylesheets/components/blog/_article.scss
> +  z-index: 20;
I'll need to double check this, but I believe so.

2017-07-16 05:01 UTC, benjaminmodayil commented on src/stylesheets/components/blog/_article.scss
> +  width: rd(950, 1440);
The max-width is a cover all solution. So for screens 1440px and lower, the percentage of the screen of this block will take up 950px (69.5%) of the screen. But if the screen size is larger the max that percentage can expand is up to 1200px.

2017-07-18 14:46 UTC, merged